name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    name: UI tests (iOS ${{ matrix.config.version }})
    runs-on: ${{ matrix.config.system }}
    strategy:
      matrix:
        config:
          - version: '15.2'
            device: 'iPhone 13'
            system: macos-11
          - version: '16.2'
            device: 'iPhone 14'
            system: macos-12
          - version: '17.2'
            device: 'iPhone 15'
            system: macos-13
          - version: '18.2'
            device: 'iPhone 16'
            system: macos-14
          - version: '26.0'
            device: 'iPhone 17'
            system: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          xcodebuild test -project Sample/Sample.xcodeproj -scheme Sample -destination "platform=iOS Simulator,OS=${{ matrix.config.version }},name=${{ matrix.config.device }}"
