name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    name: UI tests (iOS ${{ matrix.config.version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - version: '16.4'
            device: 'iPhone 14'
          - version: '17.5'
            device: 'iPhone 15'
          - version: '18.6'
            device: 'iPhone 16'
          - version: '26.0.1'
            device: 'iPhone 17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare runtime
        id: check-runtime
        run: |
          available_runtimes="$(xcrun simctl list runtimes available)"
          echo "$available_runtimes"

          if echo "$available_runtimes" | grep -q "^iOS ${{ matrix.config.version }}"; then
            echo "iOS ${{ matrix.config.version }} runtime is available"
          else
            sudo xcodes runtimes install "iOS ${{ matrix.config.version }}"
          fi

      - name: Run tests
        run: |
          xcodebuild test -project Sample/Sample.xcodeproj -scheme Sample -destination "platform=iOS Simulator,OS=${{ matrix.config.version }},name=${{ matrix.config.device }}"
